name: java CI 

on:
  push: 
    branches : [main]
  pull_request :
    branches : [main]

jobs :
  build :
    runs-on : ubuntu-latest

    steps: 
      - name: checkout code
        uses : actions/checkout@v4

      - name : setup JDK
        uses : actions/setup-java@v4
        with:
          java-version : '21'
          distribution : 'temurin'

      - name : build app
        run : mvn -B clean package 
